stages:
  - build
  - deploy

#####################################
# Étape 1 : Build & Push Docker Image
#####################################
build:
  stage: build
  image: node:20
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_TLS_VERIFY: "0"  # Désactiver la vérification TLS
    DOCKER_DRIVER: overlay2
    NODE_ENV: production
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
      - .npm/
  before_script:
    - echo "Vérification de la connexion à Docker..."
    - until docker info > /dev/null 2>&1; do echo "Docker n'est pas encore prêt..."; sleep 1; done
  
  script:
    - rm -rf node_modules
    - npm cache clean --force
    - if [ ! -f package-lock.json ]; then npm install --package-lock-only; fi
    - npm ci --legacy-peer-deps  # ✅ Correction ici
    - export NODE_OPTIONS=--max_old_space_size=8192
    - npm run build
    - docker build -t docker.io/$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest -f Dockerfile.prod .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push docker.io/$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest
    - docker images
  only:
    - main

#####################################
# Étape 2 : Déploiement sur le serveur
#####################################
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client sshpass
    - echo "$SERVER_SSH_KEY" > id_rsa
    - chmod 600 id_rsa
    - echo "$SERVER_SSH_KNOWN_HOSTS" > known_hosts
    - if [ -n "$SERVER_IP" ]; then ssh-keyscan -t ed25519 $SERVER_IP >> known_hosts; else echo "SERVER_IP is not set"; fi
    - eval $(ssh-agent -s) && ssh-add id_rsa  # Ajout de la clé SSH à l'agent
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker pull docker.io/$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest
    - >
      ssh -i id_rsa -o UserKnownHostsFile=known_hosts -o StrictHostKeyChecking=yes $SERVER_USER@$SERVER_IP "
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD &&
        docker pull docker.io/$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest &&
        docker stop nuxt-container || true &&
        docker rm nuxt-container || true &&
        docker run -d --restart=always -p 3000:3000 --name nuxt-container docker.io/$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest
      "
  after_script:
    - rm -f id_rsa known_hosts  # Nettoyage des fichiers sensibles
  only:
    - main